default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  host: <%= ENV["DATABASE_HOST"] || "192.168.0.2" %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: send_money_development

test:
  <<: *default
  database: send_money_test

# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
production:
  primary: &primary_production
    <<: *default
    database: send_money_production
    username: send_money
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: send_money_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: send_money_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: send_money_production_cable
    migrations_paths: db/cable_migrate
